# Generated by Django 6.0 on 2025-12-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='divergencias/')),
                ('tem_graus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='materias/')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('divergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graus', to='conteudo.divergencia')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo_pdf', models.FileField(upload_to='pdfs/')),
                ('divergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.divergencia')),
                ('grau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conteudo.grau')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.materia')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.serie')),
            ],
        ),
    ]
