# Generated by Django 6.0 on 2025-12-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='materias',
            field=models.ManyToManyField(related_name='series', to='conteudo.materia'),
        ),
    ]
