# Generated by Django 6.0 on 2025-12-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_serie_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='divergencia',
            name='destaque_home',
            field=models.BooleanField(default=False, verbose_name='Aparecer na Home?'),
        ),
    ]
