# Generated by Django 6.0 on 2025-12-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_divergencia_destaque_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='divergencia',
            name='emoji',
            field=models.CharField(blank=True, default='🟣', help_text='Copie e cole um emoji aqui', max_length=10),
        ),
        migrations.AlterField(
            model_name='divergencia',
            name='destaque_home',
            field=models.BooleanField(default=False),
        ),
    ]
