# Generated by Django 6.0 on 2025-12-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0004_divergencia_emoji_alter_divergencia_destaque_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divergencia',
            name='emoji',
        ),
        migrations.AlterField(
            model_name='divergencia',
            name='destaque_home',
            field=models.BooleanField(default=False, verbose_name='Aparecer na Home?'),
        ),
    ]
