# Generated by Django 6.0 on 2025-12-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0006_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='materias',
        ),
        migrations.AddField(
            model_name='materia',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='materias', to='conteudo.serie'),
        ),
    ]
