# Generated by Django 6.0 on 2025-12-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0007_remove_serie_materias_materia_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='divergencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conteudo.divergencia'),
        ),
        migrations.AddField(
            model_name='serie',
            name='grau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conteudo.grau'),
        ),
    ]
