# Generated by Django 6.0 on 2025-12-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0008_serie_divergencia_serie_grau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='series',
        ),
        migrations.AddField(
            model_name='materia',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='conteudo.serie'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='slug',
            field=models.SlugField(),
        ),
    ]
