# Generated by Django 6.0 on 2025-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0009_remove_materia_imagem_remove_materia_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
