# Generated by Django 6.0 on 2025-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0010_alter_serie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='Projeto-Sonar/media/perfis/default.png', upload_to='perfis/'),
        ),
    ]
