# Generated by Django 6.0 on 2025-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0011_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='perfis/default.png', upload_to='perfis/'),
        ),
    ]
